version: "3.5"

services:
  bot:
    container_name: bot
    restart: always
    build:
      context: .
      dockerfile: Docker/bot.Dockerfile
    env_file:
      - .env
    environment:
      POSTGRES_DSN: "postgresql+asyncpg://postgres:${POSTGRES_PASSWORD}@postgres:5432/bot"
      REDIS_DSN: "redis://default:${REDIS_PASSWORD}@cache:6379/0"
    volumes:
      - ./:/app

  scheduler:
    container_name: scheduler
    restart: always
    build:
      context: .
      dockerfile: Docker/scheduler.Dockerfile
    env_file:
      - .env

  cache:
    image: redis:latest
    restart: always
    ports:
      - '6381:6379'
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data

  postgres:
    container_name: postgres
    build:
      context: ./Docker
      dockerfile: db.Dockerfile
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  redis_data:
