version: "3.5"

services:
  bot:
    container_name: bot
    build:
      context: .
      dockerfile: Docker/bot.Dockerfile
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DSN: "postgresql+psycopg2://postgres:${POSTGRES_PASSWORD}@postgres:5432/bot"
    volumes:
      - ./:/app

  postgres:
    container_name: postgres
    build:
      context: ./Docker
      dockerfile: db.Dockerfile
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
